# Generated by Django 3.1.4 on 2020-12-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portfoilio',
            new_name='Portfolio',
        ),
    ]
